#!/usr/bin/env bats
# shellcheck disable=SC2016  # backticks here are markdown, matched literally
#
# What this project is called, and that the generated README says it too.
#
# The repository was renamed from `ib-gateway-docker` to `ib-docker` on
# 2026-08-27: one compose file now runs IB Gateway, TWS and the bastion, so a
# name naming only the gateway had stopped being true. Two strings deliberately
# keep the old name and must not be swept up by a later rename:
#
#   * `gnzsnz/ib-gateway-docker` - the project this was forked from. Credit,
#     and a repository nobody here can rename.
#   * the vendored copy inside the Investio repository, which is a directory in
#     somebody else's tree.
#
# The README check is the one `CLAUDE.md` asks for under *Rules vs. checks*: it
# is generated by `envsubst` in `detect-releases.yml`, so an edit made to
# `README.md` instead of `template_README.md` survives until the next IB
# release and then vanishes. This catches it in the same commit.

setup() {
	ROOT="$(cd "${BATS_TEST_DIRNAME}/../.." && pwd)"
}

# Every file in the tree, minus what is not ours to name.
#
# `find` + `grep`, not `grep -r --exclude-dir`: bats runs on BusyBox grep,
# which rejects both --exclude-dir and --binary-files and exits 1. With the
# `|| true` below that made this search return nothing at all, so the assertion
# passed no matter what the tree said. Verified by reverting one occurrence and
# watching it stay green.
#
# `.git` is excluded by name as well as by path: in a worktree it is a *file*
# holding the path of the main checkout, which still has the old name in it.
tree_grep() {
	find "$ROOT" \
		-name .git -prune -o \
		-name .venv -prune -o \
		-name .claude -prune -o \
		-type f -exec grep -n -- "$1" /dev/null {} + 2>/dev/null || true
}

@test "naming: nothing points at this repository by its old name" {
	local hits
	# `dennisdeh/ib-gateway-docker`, not the bare string: the owner-qualified
	# form is what a URL, a git remote and a `uses:` reference are built from,
	# and it is the one that breaks a build - `Dockerfile.template` fetches the
	# installers from `github.com/dennisdeh/<repo>/releases/...` with `curl -f`.
	# The bare name still occurs in prose describing the rename, and in
	# `gnzsnz/ib-gateway-docker` and the Investio path; none of those resolve to
	# anything here, so matching them would only train people to ignore this.
	#
	# `|| true`: grep exits 1 when it finds nothing, which is the passing case.
	hits="$(tree_grep 'dennisdeh/ib-gateway-docker' |
		grep -v "$(basename "${BATS_TEST_FILENAME}")" || true)"
	[ -z "$hits" ] || {
		echo "the repository is 'ib-docker'; these still point at the old name:"
		echo "$hits"
		return 1
	}
}

@test "naming: the upstream credit keeps the name it actually has" {
	# Renaming this repository does not rename the one it was forked from.
	run grep -rF 'gnzsnz/ib-gateway-docker' "${ROOT}/README.md" "${ROOT}/template_README.md"
	[ "$status" -eq 0 ]
}

@test "naming: the published image names are unchanged" {
	# The rename was of the repository, not of the packages. These are what
	# users pull and what Dockerfile.tws opens FROM.
	run grep -rqF 'ghcr.io/dennisdeh/ib-gateway' "${ROOT}/docker-compose.yml"
	[ "$status" -eq 0 ]
	run grep -rqF 'ghcr.io/dennisdeh/tws-rdesktop' "${ROOT}/.github/workflows/publish.yml"
	[ "$status" -eq 0 ]
	# The bastion publishes from its own workflow since 2026-08-30.
	run grep -rqF 'ghcr.io/dennisdeh/bastion' "${ROOT}/.github/workflows/publish-bastion.yml"
	[ "$status" -eq 0 ]
}

# The seven variables the "Update README" step of detect-releases.yml
# substitutes, and where it reads each from. Kept in one place so the two tests
# below and that step cannot drift apart.
readme_vars() {
	local latest stable
	latest="$(grep 'ENV IB_GATEWAY_VERSION=' "${ROOT}/latest/Dockerfile" | head -1 | cut -d '=' -f2)"
	stable="$(grep 'ENV IB_GATEWAY_VERSION=' "${ROOT}/stable/Dockerfile" | head -1 | cut -d '=' -f2)"
	echo "LATEST_VERSION=${latest}"
	echo "STABLE_VERSION=${stable}"
	echo "LATEST_MINOR=$(cut -d '.' -f1,2 <<<"$latest")"
	echo "STABLE_MINOR=$(cut -d '.' -f1,2 <<<"$stable")"
	# Per channel, from the channel's own Dockerfile - not once from
	# Dockerfile.template. detect-ibc-release.yml bumps the template alone, so
	# the template says what the *next* release will ship while the two
	# channels can legitimately hold different IBC versions; one number would
	# be wrong for one of the rows. See docs/DECISIONS.md #2 and #26.
	echo "LATEST_IBC=$(grep 'ENV IBC_VERSION' "${ROOT}/latest/Dockerfile" | head -1 | cut -d '=' -f2)"
	echo "STABLE_IBC=$(grep 'ENV IBC_VERSION' "${ROOT}/stable/Dockerfile" | head -1 | cut -d '=' -f2)"
	# The bastion has no IB version; its own Dockerfile declares one, and this
	# is the expression publish.yml tags the published image with.
	echo "BASTION_VERSION=$(sed -n 's/^ARG IMAGE_VERSION=//p' "${ROOT}/bastion/Dockerfile" | head -1)"
}

@test "README.md is exactly what the release workflow generates" {
	# Same variables, same sources, same substitution as that step. envsubst is
	# not in the bats image, and the template only ever uses the ${VAR} form,
	# so sed reproduces it exactly.
	local expected="${BATS_TEST_TMPDIR}/README.expected" line name value
	cp "${ROOT}/template_README.md" "$expected"
	while IFS= read -r line; do
		name="${line%%=*}"
		value="${line#*=}"
		[ -n "$value" ] || {
			echo "no value found for \$${name}"
			return 1
		}
		sed -i "s|\${${name}}|${value}|g" "$expected"
	done < <(readme_vars)

	diff -q "$expected" "${ROOT}/README.md" >/dev/null || {
		echo "README.md is not envsubst(template_README.md) for the versions in"
		echo "this tree. Edit template_README.md, then regenerate - a change"
		echo "written straight into README.md is lost at the next IB release."
		diff -u "$expected" "${ROOT}/README.md" || true
		return 1
	}
}

@test "README.md leaves none of the substituted placeholders behind" {
	# Only these are substituted. The README documents `${PWD}`, `${IB_APP}`,
	# `${IBC_VERSION}` and `${IB_GATEWAY_VERSION}` as literal text naming a
	# variable the reader sets, so a blanket search for `${...}` would fail on
	# its own examples.
	run grep -nE '\$\{(LATEST_VERSION|LATEST_MINOR|LATEST_IBC|STABLE_VERSION|STABLE_MINOR|STABLE_IBC|BASTION_VERSION)\}' \
		"${ROOT}/README.md"
	[ "$status" -ne 0 ] || {
		echo "unsubstituted placeholders in the generated README:"
		echo "$output"
		return 1
	}
}

@test "README.md reports each channel's own IBC version" {
	# The defect this replaced: one ${IBC_VERSION} filled both rows, so the
	# table claimed stable shipped whatever latest did.
	local latest_ibc stable_ibc
	latest_ibc="$(grep 'ENV IBC_VERSION' "${ROOT}/latest/Dockerfile" | head -1 | cut -d '=' -f2)"
	stable_ibc="$(grep 'ENV IBC_VERSION' "${ROOT}/stable/Dockerfile" | head -1 | cut -d '=' -f2)"

	run grep -F '| [ib-gateway][1] | `latest` | ' "${ROOT}/README.md"
	[ "$status" -eq 0 ]
	[[ $output == *"\`${latest_ibc}\`"* ]] || {
		echo "the latest row does not name IBC ${latest_ibc}: ${output}"
		return 1
	}

	run grep -F '| [ib-gateway][1] |`stable` | ' "${ROOT}/README.md"
	[ "$status" -eq 0 ]
	[[ $output == *"\`${stable_ibc}\`"* ]] || {
		echo "the stable row does not name IBC ${stable_ibc}: ${output}"
		return 1
	}
}
