#!/usr/bin/env bats
#
# What this project is called, and that the generated README says it too.
#
# The repository was renamed from `ib-gateway-docker` to `ib-docker` on
# 2026-08-27: one compose file now runs IB Gateway, TWS and the bastion, so a
# name naming only the gateway had stopped being true. Two strings deliberately
# keep the old name and must not be swept up by a later rename:
#
#   * `gnzsnz/ib-gateway-docker` - the project this was forked from. Credit,
#     and a repository nobody here can rename.
#   * the vendored copy inside the Investio repository, which is a directory in
#     somebody else's tree.
#
# The README check is the one `CLAUDE.md` asks for under *Rules vs. checks*: it
# is generated by `envsubst` in `detect-releases.yml`, so an edit made to
# `README.md` instead of `template_README.md` survives until the next IB
# release and then vanishes. This catches it in the same commit.

setup() {
	ROOT="$(cd "${BATS_TEST_DIRNAME}/../.." && pwd)"
}

# Every file in the tree, minus what is not ours to name.
#
# `find` + `grep`, not `grep -r --exclude-dir`: bats runs on BusyBox grep,
# which rejects both --exclude-dir and --binary-files and exits 1. With the
# `|| true` below that made this search return nothing at all, so the assertion
# passed no matter what the tree said. Verified by reverting one occurrence and
# watching it stay green.
#
# `.git` is excluded by name as well as by path: in a worktree it is a *file*
# holding the path of the main checkout, which still has the old name in it.
tree_grep() {
	find "$ROOT" \
		-name .git -prune -o \
		-name .venv -prune -o \
		-name .claude -prune -o \
		-type f -exec grep -n -- "$1" /dev/null {} + 2>/dev/null || true
}

@test "naming: nothing points at this repository by its old name" {
	local hits
	# `dennisdeh/ib-gateway-docker`, not the bare string: the owner-qualified
	# form is what a URL, a git remote and a `uses:` reference are built from,
	# and it is the one that breaks a build - `Dockerfile.template` fetches the
	# installers from `github.com/dennisdeh/<repo>/releases/...` with `curl -f`.
	# The bare name still occurs in prose describing the rename, and in
	# `gnzsnz/ib-gateway-docker` and the Investio path; none of those resolve to
	# anything here, so matching them would only train people to ignore this.
	#
	# `|| true`: grep exits 1 when it finds nothing, which is the passing case.
	hits="$(tree_grep 'dennisdeh/ib-gateway-docker' |
		grep -v "$(basename "${BATS_TEST_FILENAME}")" || true)"
	[ -z "$hits" ] || {
		echo "the repository is 'ib-docker'; these still point at the old name:"
		echo "$hits"
		return 1
	}
}

@test "naming: the upstream credit keeps the name it actually has" {
	# Renaming this repository does not rename the one it was forked from.
	run grep -rF 'gnzsnz/ib-gateway-docker' "${ROOT}/README.md" "${ROOT}/template_README.md"
	[ "$status" -eq 0 ]
}

@test "naming: the published image names are unchanged" {
	# The rename was of the repository, not of the packages. These are what
	# users pull and what Dockerfile.tws opens FROM.
	run grep -rqF 'ghcr.io/dennisdeh/ib-gateway' "${ROOT}/docker-compose.yml"
	[ "$status" -eq 0 ]
	run grep -rqF 'ghcr.io/dennisdeh/tws-rdesktop' "${ROOT}/.github/workflows/publish.yml"
	[ "$status" -eq 0 ]
	run grep -rqF 'ghcr.io/dennisdeh/bastion' "${ROOT}/.github/workflows/publish.yml"
	[ "$status" -eq 0 ]
}

@test "README.md is exactly what the release workflow generates" {
	# The same five variables, substituted the same way, from the same sources
	# as the "Update README" step of detect-releases.yml. envsubst is not in
	# the bats image, and the template only ever uses the ${VAR} form.
	local latest stable latest_minor stable_minor ibc
	latest="$(grep 'ENV IB_GATEWAY_VERSION=' "${ROOT}/latest/Dockerfile" | head -1 | cut -d '=' -f2)"
	stable="$(grep 'ENV IB_GATEWAY_VERSION=' "${ROOT}/stable/Dockerfile" | head -1 | cut -d '=' -f2)"
	latest_minor="$(cut -d '.' -f1,2 <<<"$latest")"
	stable_minor="$(cut -d '.' -f1,2 <<<"$stable")"
	ibc="$(grep 'ENV IBC_VERSION' "${ROOT}/Dockerfile.template" | cut -d '=' -f 2)"

	sed -e "s|\${LATEST_VERSION}|${latest}|g" \
		-e "s|\${STABLE_VERSION}|${stable}|g" \
		-e "s|\${LATEST_MINOR}|${latest_minor}|g" \
		-e "s|\${STABLE_MINOR}|${stable_minor}|g" \
		-e "s|\${IBC_VERSION}|${ibc}|g" \
		"${ROOT}/template_README.md" >"${BATS_TEST_TMPDIR}/README.expected"

	run diff -u "${BATS_TEST_TMPDIR}/README.expected" "${ROOT}/README.md"
	[ "$status" -eq 0 ] || {
		echo "README.md is not envsubst(template_README.md)."
		echo "Edit template_README.md, then regenerate - a change written"
		echo "straight into README.md is lost at the next IB release."
		echo "$output"
		return 1
	}
}

@test "README.md leaves none of the five placeholders unsubstituted" {
	# Only those five are substituted. The README documents `${PWD}`,
	# `${IB_APP}` and `${IB_GATEWAY_VERSION}` as literal text a user types, so
	# a blanket search for `${...}` would fail on its own examples.
	run grep -nE '\$\{(LATEST_VERSION|LATEST_MINOR|STABLE_VERSION|STABLE_MINOR|IBC_VERSION)\}' \
		"${ROOT}/README.md"
	[ "$status" -ne 0 ] || {
		echo "unsubstituted placeholders in the generated README:"
		echo "$output"
		return 1
	}
}
